// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX3uRbX4DX7rdOibz_aSD8dNpC_OZvnqE',
    appId: '1:430920912734:web:35c592c6e1331ff3ab09cf',
    messagingSenderId: '430920912734',
    projectId: 'fintechda-cfba5',
    authDomain: 'fintechda-cfba5.firebaseapp.com',
    storageBucket: 'fintechda-cfba5.firebasestorage.app',
    measurementId: 'G-KZLYPDRPWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPQ7qfWP2ZUhE3VzQCqJcrnYbkWcWBgH8',
    appId: '1:430920912734:android:1f0fc0bbe2d38888ab09cf',
    messagingSenderId: '430920912734',
    projectId: 'fintechda-cfba5',
    storageBucket: 'fintechda-cfba5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhlHJG5Qp5iVbQo92yYudBerZGFOBxcOM',
    appId: '1:430920912734:ios:b56c8bc97dfb7770ab09cf',
    messagingSenderId: '430920912734',
    projectId: 'fintechda-cfba5',
    storageBucket: 'fintechda-cfba5.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhlHJG5Qp5iVbQo92yYudBerZGFOBxcOM',
    appId: '1:430920912734:ios:b56c8bc97dfb7770ab09cf',
    messagingSenderId: '430920912734',
    projectId: 'fintechda-cfba5',
    storageBucket: 'fintechda-cfba5.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX3uRbX4DX7rdOibz_aSD8dNpC_OZvnqE',
    appId: '1:430920912734:web:af246ae2e4d00c2dab09cf',
    messagingSenderId: '430920912734',
    projectId: 'fintechda-cfba5',
    authDomain: 'fintechda-cfba5.firebaseapp.com',
    storageBucket: 'fintechda-cfba5.firebasestorage.app',
    measurementId: 'G-RJ52JB7FXC',
  );
}
